### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by manpreet-singh**
Trying to move everything to the master branch, (This may or may not mess things up)

### CODE REVIEW

**Comment by skallaher** [comment]
If you would like to overwrite the master branch with the dev branch, you can do a merge and overwrite any changes from this commit: 6f35dbf (Title: "Configuration updates. Some minor refinements."). Or, alternatively, you can try a rebase of dev onto master. You can look up what each one does if you want to be sure to choose the correct option.

**Comment by MrZoraman** [comment]
Or you guys could actually do a merge. Netbeans has a pretty nice branch merging system built in. It's well worth getting to know, albeit the learning curve is a little steep.

EDIT: You guys haven't pushed in 9 months... It's probably best just to do a force push. This will overwrite everything in the current github repository! This is a pretty scary thing to do, but is probably the best course of action in your case. Due to the implications of such an action, netbeans has no built in way to do this (It's not a bug, it's a feature!). You'll have to navigate to the root directory of your project in the command line (or shift+right click -> open command window here) and execute "git push origin master --force". 

EDIT 2: You guys really should push to the remote repository (github) at the end of each day to 1: backup your progress and 2: so you don't have to deal with these shenanigans.

EDIT 3: I don't really have an edit 3, but 3 is a nice number.

**Comment by skallaher** [comment]
Eclipse has a similar system called Egit if you'd like to go that route also.

**Comment by manpreet-singh** [comment]
Fixed the problem through bash

**Pull request merged**
